source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
gem 'sinatra-contrib'
gem 'mysql2'
gem 'tux'
gem 'puma'
gem 'shotgun'